kind: Service
apiVersion: v1
metadata:
  name: metabolic-ninja-production
spec:
  selector:
    app: metabolic-ninja
    env: production
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: rabbitmq
    protocol: TCP
    port: 5672
    targetPort: 5672
