kind: Service
apiVersion: v1
metadata:
  name: metabolic-ninja-staging
spec:
  selector:
    app: metabolic-ninja
    env: staging
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8000
