"""empty message

Revision ID: 50797eac2009
Revises: 6519ae509e6d
Create Date: 2018-12-04 16:01:24.519977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50797eac2009'
down_revision = '6519ae509e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('max_predictions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_job', 'max_predictions')
    # ### end Alembic commands ###
