"""empty message

Revision ID: 6519ae509e6d
Revises: d4b4218a21c8
Create Date: 2018-12-04 15:03:45.669665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6519ae509e6d'
down_revision = 'd4b4218a21c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('product_name', sa.String(), nullable=False))
    op.drop_column('design_job', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('design_job', 'product_name')
    # ### end Alembic commands ###
