"""empty message

Revision ID: 7142dbafe154
Revises: 03ed52ee71eb
Create Date: 2018-11-08 07:51:50.333410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7142dbafe154'
down_revision = '03ed52ee71eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_job', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
