"""empty message

Revision ID: d4b4218a21c8
Revises: 03ed52ee71eb
Create Date: 2018-12-04 12:30:38.530918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b4218a21c8'
down_revision = '03ed52ee71eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_job', sa.Column('product', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_job', 'product')
    # ### end Alembic commands ###
